import { MockRequest } from '@delon/mock';

const list: any[] = [];
const total = 50;

for (let i = 0; i < total; i += 1) {
  list.push({
    id: i + 1,
    disabled: i % 6 === 0,
    href: 'https://ant.design',
    avatar: [
      'https://gw.alipayobjects.com/zos/rmsportal/eeHMaZBwmTvLdIwMfBpg.png',
      'https://gw.alipayobjects.com/zos/rmsportal/udxAbMEhpwthVVcjLXik.png'
    ][i % 2],
    no: `TradeCode ${i}`,
    title: `一个任务名称 ${i}`,
    owner: '曲丽丽',
    description: '这是一段描述',
    callNo: Math.floor(Math.random() * 1000),
    status: Math.floor(Math.random() * 10) % 4,
    updatedAt: new Date(`2017-07-${Math.floor(i / 2) + 1}`),
    createdAt: new Date(`2017-07-${Math.floor(i / 2) + 1}`),
    progress: Math.ceil(Math.random() * 100)
  });
}

function genData(params: any): { total: number; list: any[] } {
  let ret = [...list];
  const pi = +params.pi;
  const ps = +params.ps;
  const start = (pi - 1) * ps;

  if (params.no) {
    ret = ret.filter(data => data.no.indexOf(params.no) > -1);
  }

  return { total: ret.length, list: ret.slice(start, ps * pi) };
}

function saveData(id: number, value: any): { msg: string } {
  const item = list.find(w => w.id === id);
  if (!item) {
    return { msg: '无效用户信息' };
  }
  Object.assign(item, value);
  return { msg: 'ok' };
}

export const USERS = {
  '/user': (req: MockRequest) => genData(req.queryString),
  '/user/:id': (req: MockRequest) => list.find(w => w.id === +req.params.id),
  'POST /user/:id': (req: MockRequest) => saveData(+req.params.id, req.body),
  '/user/current': {
    name: 'Cipchk',
    avatar: 'https://gw.alipayobjects.com/zos/rmsportal/BiazfanxmamNRoxxVxka.png',
    userid: '00000001',
    email: 'cipchk@qq.com',
    signature: '海纳百川，有容乃大',
    title: '交互专家',
    group: '蚂蚁金服－某某某事业群－某某平台部－某某技术部－UED',
    tags: [
      {
        key: '0',
        label: '很有想法的'
      },
      {
        key: '1',
        label: '专注撩妹'
      },
      {
        key: '2',
        label: '帅~'
      },
      {
        key: '3',
        label: '通吃'
      },
      {
        key: '4',
        label: '专职后端'
      },
      {
        key: '5',
        label: '海纳百川'
      }
    ],
    notifyCount: 12,
    country: 'China',
    geographic: {
      province: {
        label: '上海',
        key: '330000'
      },
      city: {
        label: '市辖区',
        key: '330100'
      }
    },
    address: 'XX区XXX路 XX 号',
    phone: '你猜-你猜你猜猜猜'
  },
  'POST /user/avatar': 'ok',
  'POST /login/account': (req: MockRequest) => {
    const data = req.body;
    if (!(data.userName === 'admin' || data.userName === 'user') || data.password !== 'ng-alain.com') {
      return { msg: `Invalid username or password（admin/ng-alain.com）` };
    }
    return {
      msg: 'ok',
      user: {
        token: '123456789',
        name: data.userName,
        email: `${data.userName}@qq.com`,
        id: 10000,
        time: +new Date()
      }
    };
  },
  'POST /system/auth/oauth/token': (req: MockRequest) => {
    return {
      access_token:
        'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJvcmdhbiI6eyJvcmdhbklkIjoiMSIsIm9yZ2FuTmFtZSI6Iuays-WMl-ecgeeUn-aAgeeOr-Wig-WOhSIsIm9yZ2FuQ29kZSI6IjEzMDAwMDAwMCIsIm9yZ2FuRGVzYyI6IuacuuaehOaPj-i_sDAwMSIsIm9yZ2FuVHlwZSI6IjEiLCJwYXJlbnRJZCI6IjAiLCJvcmdhblBhdGgiOiIvMSIsIm9yZGVyTnVtIjowLCJlbmFibGUiOiIxIiwicGFyZW50VW5pdCI6IjEiLCJvcmdhbktpbmQiOiIxIn0sImxvZ2luSWQiOiJhZG1pbiIsImF1dGgiOiJBVVRIX0FETUlOLEFVVEhfQUlSLEFVVEhfQUlSX0RBVEFfQVVESVQxLEFVVEhfQUlSX0RFUFRfTUFOQUdFLEFVVEhfQUlSX1VTRVJfTUFOQUdFLEFVVEhfQk9PSyxBVVRIX0NPQUxfQURNSU4sQVVUSF9DT0FMX0JBU0UsQVVUSF9ESVNQQVRDSF9NQVBfQURNSU4sQVVUSF9FUl9FTUVSR0VOQ1lfQ0VOVEVSLEFVVEhfRkJKRF9HS1BULEFVVEhfRkJKRF9IQixBVVRIX0ZCSkRfVFJBTlNNSVQsQVVUSF9GVVJOQUNFX1NIRU5HLEFVVEhfRlVSTkFDRV9TSEksQVVUSF9GVVJOQUNFX1hJQU4sQVVUSF9PTF9DSVRZX0pDSixBVVRIX09QRVJBVEVfT1BFUkFURV9aRixBVVRIX1BEQV9BTExfUFVCTElDLEFVVEhfUERBX0FMTF9QVUJMSUNfQVBQLEFVVEhfUERBX0FQUExZX0FVRElULEFVVEhfUERBX0NIVVpISURBTkZVSEUsQVVUSF9QREFfQ09BTF9RVUFMSVRZX0FQUCxBVVRIX1BEQV9JTlNQRUNUQ0hFQ0tfQVBQLEFVVEhfUERBX1NIRU5HX0xFQURFUixBVVRIX1BEQV9TSEVOR19MRUFERVJfQVBQLEFVVEhfUERBX1NIRU5HX05PUk1BTF9BUFAsQVVUSF9QREFfU0hFTkdfUkFORE9NLEFVVEhfUERBX1NIRU5HX1JBTkRPTV9BUFAsQVVUSF9QREFfU0hFTkdfVElQU1RBRkYsQVVUSF9QREFfU0hFTkdfVElQU1RBRkZfQVBQLEFVVEhfUERBX1NQRUNJQUxCQUlZQU5HRElBTl9BUFAsQVVUSF9QREFfU1BFQ0lBTElOU1BFQ1RPUl9BUFAsQVVUSF9QREFfVElQU1RBRkZfTUFOQUdFLEFVVEhfUFNETVBST1hZX0FETUlOLEFVVEhfVE9LRU4sQVVUSF9WRF9NRU5VX01BTkFHRVIsQVVUSF9YWkNGLEFVVEhfWkhQU19QUyxhdXRoX3VuaWZpZWRiYXNlaW5mb19hZG1pbizkuInnur_kuIDljZXmnYPpmZAiLCJ1c2VyX25hbWUiOiJhZG1pbiIsInJvbGVzIjoiUk9MRV9QREFfU0hFTkdfUkFORE9NLFJPTEVfQURNSU4sUk9MRV9YWkNGLFJPTEVfUERBX1NIRU5HX1RJUFNUQUZGLFJPTEVfQ09BTCxST0xFX0ZVUk5BQ0VfQURNSU4sUk9MRV9QU0RNUFJPWFlfQURNSU4sUk9MRV9QREFfU1BFQ0lBTEJBSVlBTkdESUFOLFJPTEVfRkJKRF9IQixST0xFX1BEQV9BTExfUFVCTElDLFJPTEVfVkRfTV9NRU5VLFJPTEVfUERBX1NIRU5HX0xFQURFUixST0xFX1BEQV9TSEVOR19OT1JNQUwscm9sZV91bmlmaWVkYmFzZWluZm9fYWRtaW4sUk9MRV9BSVJfSFVBTkJBT0pVLFJPTEVfRElTUEFUQ0hfTUFQX0FETUlOLFJPTEVfUERBX1JBTkRPTV9GTEFHIiwibW9iaWxlIjoiMTM2MjMzMTAzMzciLCJpc3MiOiIiLCJhdXRob3JpdGllcyI6WyJBVVRIX0RJU1BBVENIX01BUF9BRE1JTiIsIkFVVEhfQUlSIiwiQVVUSF9GVVJOQUNFX1NIRU5HIiwiQVVUSF9QREFfU0hFTkdfVElQU1RBRkZfQVBQIiwiQVVUSF9QREFfU0hFTkdfTEVBREVSX0FQUCIsIkFVVEhfQk9PSyIsIkFVVEhfUERBX0NPQUxfUVVBTElUWV9BUFAiLCJBVVRIX0FETUlOIiwiQVVUSF9BSVJfVVNFUl9NQU5BR0UiLCJBVVRIX09QRVJBVEVfT1BFUkFURV9aRiIsIkFVVEhfUERBX1NIRU5HX0xFQURFUiIsIkFVVEhfUERBX1NIRU5HX1JBTkRPTSIsIkFVVEhfRlVSTkFDRV9TSEkiLCJBVVRIX0FJUl9ERVBUX01BTkFHRSIsIkFVVEhfUERBX1NQRUNJQUxJTlNQRUNUT1JfQVBQIiwiQVVUSF9QREFfVElQU1RBRkZfTUFOQUdFIiwiQVVUSF9QREFfQUxMX1BVQkxJQyIsImF1dGhfdW5pZmllZGJhc2VpbmZvX2FkbWluIiwiQVVUSF9QREFfU0hFTkdfTk9STUFMX0FQUCIsIkFVVEhfRVJfRU1FUkdFTkNZX0NFTlRFUiIsIkFVVEhfT0xfQ0lUWV9KQ0oiLCJBVVRIX0ZCSkRfR0tQVCIsIkFVVEhfUFNETVBST1hZX0FETUlOIiwiQVVUSF9UT0tFTiIsIkFVVEhfQ09BTF9BRE1JTiIsIkFVVEhfQUlSX0RBVEFfQVVESVQxIiwiQVVUSF9QREFfU0hFTkdfUkFORE9NX0FQUCIsIkFVVEhfWFpDRiIsIkFVVEhfUERBX1NQRUNJQUxCQUlZQU5HRElBTl9BUFAiLCJBVVRIX0NPQUxfQkFTRSIsIkFVVEhfRkJKRF9UUkFOU01JVCIsIkFVVEhfUERBX1NIRU5HX1RJUFNUQUZGIiwi5LiJ57q_5LiA5Y2V5p2D6ZmQIiwiQVVUSF9aSFBTX1BTIiwiQVVUSF9GQkpEX0hCIiwiQVVUSF9WRF9NRU5VX01BTkFHRVIiLCJBVVRIX1BEQV9JTlNQRUNUQ0hFQ0tfQVBQIiwiQVVUSF9QREFfQ0hVWkhJREFORlVIRSIsIkFVVEhfRlVSTkFDRV9YSUFOIiwiQVVUSF9QREFfQUxMX1BVQkxJQ19BUFAiLCJBVVRIX1BEQV9BUFBMWV9BVURJVCJdLCJjbGllbnRfaWQiOiJiZHAiLCJyZWFsTmFtZSI6IueuoeeQhuWRmCIsImF1ZCI6WyJiZHAtY29yZSIsInN5cy1zZXJ2ZXIiLCJ6aHBzLXJlbGF0aW9uIiwic3lzIiwiemhwcy1jb3JlIiwiY2xpZW50LXJlc291cmNlIl0sInNjb3BlIjpbInJlYWQiLCJ3cml0ZSIsInRydXN0Il0sImlkIjoiMTEiLCJleHAiOjE2NzUxNzU2MzYsImp0aSI6ImZhYTIxMDBkLWVkYWUtNDg0Mi04ODYzLWIzOGE4OGNmMDM4ZSJ9.Yt7oX5uJ-WA50QT_4s9oPuKRwdhvnbHwsup_H9K0LhlyZJUooJ9Tefic_dSczHpyK-1qw-nyOAY6D2AqG74kcwKRtfWBYgyG1otS67MKpix3BeTASil207rN5-EM5KnDbze3KGM4SMSSKAyPvFc4bezt4ruXXnpK4-hCpzz2ioWJfgXTkUXwwD51V7QRkRMYjTldYdhTmPNWYncFZfvqTm4JtrR3kEo7B0J5evX-Soc4_sr41ztIk0emD1lukXoDPaHnd3Kfg7Sz6sjIigEIDUnZjdqQWs98zSLXgnCjC5LjEt8_xfq1nyBPFuJSX3I5xvcfMRKJDkdnziqUrNdOXw',
      token_type: 'bearer',
      refresh_token:
        'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJvcmdhbiI6eyJvcmdhbklkIjoiMSIsIm9yZ2FuTmFtZSI6Iuays-WMl-ecgeeUn-aAgeeOr-Wig-WOhSIsIm9yZ2FuQ29kZSI6IjEzMDAwMDAwMCIsIm9yZ2FuRGVzYyI6IuacuuaehOaPj-i_sDAwMSIsIm9yZ2FuVHlwZSI6IjEiLCJwYXJlbnRJZCI6IjAiLCJvcmdhblBhdGgiOiIvMSIsIm9yZGVyTnVtIjowLCJlbmFibGUiOiIxIiwicGFyZW50VW5pdCI6IjEiLCJvcmdhbktpbmQiOiIxIn0sImxvZ2luSWQiOiJhZG1pbiIsImF1dGgiOiJBVVRIX0FETUlOLEFVVEhfQUlSLEFVVEhfQUlSX0RBVEFfQVVESVQxLEFVVEhfQUlSX0RFUFRfTUFOQUdFLEFVVEhfQUlSX1VTRVJfTUFOQUdFLEFVVEhfQk9PSyxBVVRIX0NPQUxfQURNSU4sQVVUSF9DT0FMX0JBU0UsQVVUSF9ESVNQQVRDSF9NQVBfQURNSU4sQVVUSF9FUl9FTUVSR0VOQ1lfQ0VOVEVSLEFVVEhfRkJKRF9HS1BULEFVVEhfRkJKRF9IQixBVVRIX0ZCSkRfVFJBTlNNSVQsQVVUSF9GVVJOQUNFX1NIRU5HLEFVVEhfRlVSTkFDRV9TSEksQVVUSF9GVVJOQUNFX1hJQU4sQVVUSF9PTF9DSVRZX0pDSixBVVRIX09QRVJBVEVfT1BFUkFURV9aRixBVVRIX1BEQV9BTExfUFVCTElDLEFVVEhfUERBX0FMTF9QVUJMSUNfQVBQLEFVVEhfUERBX0FQUExZX0FVRElULEFVVEhfUERBX0NIVVpISURBTkZVSEUsQVVUSF9QREFfQ09BTF9RVUFMSVRZX0FQUCxBVVRIX1BEQV9JTlNQRUNUQ0hFQ0tfQVBQLEFVVEhfUERBX1NIRU5HX0xFQURFUixBVVRIX1BEQV9TSEVOR19MRUFERVJfQVBQLEFVVEhfUERBX1NIRU5HX05PUk1BTF9BUFAsQVVUSF9QREFfU0hFTkdfUkFORE9NLEFVVEhfUERBX1NIRU5HX1JBTkRPTV9BUFAsQVVUSF9QREFfU0hFTkdfVElQU1RBRkYsQVVUSF9QREFfU0hFTkdfVElQU1RBRkZfQVBQLEFVVEhfUERBX1NQRUNJQUxCQUlZQU5HRElBTl9BUFAsQVVUSF9QREFfU1BFQ0lBTElOU1BFQ1RPUl9BUFAsQVVUSF9QREFfVElQU1RBRkZfTUFOQUdFLEFVVEhfUFNETVBST1hZX0FETUlOLEFVVEhfVE9LRU4sQVVUSF9WRF9NRU5VX01BTkFHRVIsQVVUSF9YWkNGLEFVVEhfWkhQU19QUyxhdXRoX3VuaWZpZWRiYXNlaW5mb19hZG1pbizkuInnur_kuIDljZXmnYPpmZAiLCJ1c2VyX25hbWUiOiJhZG1pbiIsInJvbGVzIjoiUk9MRV9QREFfU0hFTkdfUkFORE9NLFJPTEVfQURNSU4sUk9MRV9YWkNGLFJPTEVfUERBX1NIRU5HX1RJUFNUQUZGLFJPTEVfQ09BTCxST0xFX0ZVUk5BQ0VfQURNSU4sUk9MRV9QU0RNUFJPWFlfQURNSU4sUk9MRV9QREFfU1BFQ0lBTEJBSVlBTkdESUFOLFJPTEVfRkJKRF9IQixST0xFX1BEQV9BTExfUFVCTElDLFJPTEVfVkRfTV9NRU5VLFJPTEVfUERBX1NIRU5HX0xFQURFUixST0xFX1BEQV9TSEVOR19OT1JNQUwscm9sZV91bmlmaWVkYmFzZWluZm9fYWRtaW4sUk9MRV9BSVJfSFVBTkJBT0pVLFJPTEVfRElTUEFUQ0hfTUFQX0FETUlOLFJPTEVfUERBX1JBTkRPTV9GTEFHIiwibW9iaWxlIjoiMTM2MjMzMTAzMzciLCJpc3MiOiIiLCJhdXRob3JpdGllcyI6WyJBVVRIX0RJU1BBVENIX01BUF9BRE1JTiIsIkFVVEhfQUlSIiwiQVVUSF9GVVJOQUNFX1NIRU5HIiwiQVVUSF9QREFfU0hFTkdfVElQU1RBRkZfQVBQIiwiQVVUSF9QREFfU0hFTkdfTEVBREVSX0FQUCIsIkFVVEhfQk9PSyIsIkFVVEhfUERBX0NPQUxfUVVBTElUWV9BUFAiLCJBVVRIX0FETUlOIiwiQVVUSF9BSVJfVVNFUl9NQU5BR0UiLCJBVVRIX09QRVJBVEVfT1BFUkFURV9aRiIsIkFVVEhfUERBX1NIRU5HX0xFQURFUiIsIkFVVEhfUERBX1NIRU5HX1JBTkRPTSIsIkFVVEhfRlVSTkFDRV9TSEkiLCJBVVRIX0FJUl9ERVBUX01BTkFHRSIsIkFVVEhfUERBX1NQRUNJQUxJTlNQRUNUT1JfQVBQIiwiQVVUSF9QREFfVElQU1RBRkZfTUFOQUdFIiwiQVVUSF9QREFfQUxMX1BVQkxJQyIsImF1dGhfdW5pZmllZGJhc2VpbmZvX2FkbWluIiwiQVVUSF9QREFfU0hFTkdfTk9STUFMX0FQUCIsIkFVVEhfRVJfRU1FUkdFTkNZX0NFTlRFUiIsIkFVVEhfT0xfQ0lUWV9KQ0oiLCJBVVRIX0ZCSkRfR0tQVCIsIkFVVEhfUFNETVBST1hZX0FETUlOIiwiQVVUSF9UT0tFTiIsIkFVVEhfQ09BTF9BRE1JTiIsIkFVVEhfQUlSX0RBVEFfQVVESVQxIiwiQVVUSF9QREFfU0hFTkdfUkFORE9NX0FQUCIsIkFVVEhfWFpDRiIsIkFVVEhfUERBX1NQRUNJQUxCQUlZQU5HRElBTl9BUFAiLCJBVVRIX0NPQUxfQkFTRSIsIkFVVEhfRkJKRF9UUkFOU01JVCIsIkFVVEhfUERBX1NIRU5HX1RJUFNUQUZGIiwi5LiJ57q_5LiA5Y2V5p2D6ZmQIiwiQVVUSF9aSFBTX1BTIiwiQVVUSF9GQkpEX0hCIiwiQVVUSF9WRF9NRU5VX01BTkFHRVIiLCJBVVRIX1BEQV9JTlNQRUNUQ0hFQ0tfQVBQIiwiQVVUSF9QREFfQ0hVWkhJREFORlVIRSIsIkFVVEhfRlVSTkFDRV9YSUFOIiwiQVVUSF9QREFfQUxMX1BVQkxJQ19BUFAiLCJBVVRIX1BEQV9BUFBMWV9BVURJVCJdLCJjbGllbnRfaWQiOiJiZHAiLCJyZWFsTmFtZSI6IueuoeeQhuWRmCIsImF1ZCI6WyJiZHAtY29yZSIsInN5cy1zZXJ2ZXIiLCJ6aHBzLXJlbGF0aW9uIiwic3lzIiwiemhwcy1jb3JlIiwiY2xpZW50LXJlc291cmNlIl0sInNjb3BlIjpbInJlYWQiLCJ3cml0ZSIsInRydXN0Il0sImF0aSI6ImZhYTIxMDBkLWVkYWUtNDg0Mi04ODYzLWIzOGE4OGNmMDM4ZSIsImlkIjoiMTEiLCJleHAiOjE2Nzc3MjQ0MzYsImp0aSI6IjcyYjAzNmJlLWMxNDMtNGRhYy1iNjg5LWI2YzdjOTk2ZWNmNCJ9.QnKksmdazhyjR1bltU5ueiDuinUc1En7Ah32THjlQX_ojUB10FvN4Yji6m7JF2MNCb-0L0RXzL1VGgfTV61C_XJ7NJzIQ0E27_PbwT4cuNSZiDxcdBVFZJ_I4yV46eg5ig9vpLvJ4CJw8-Ss8IY31I1-2X3RXMpuuX2gbPGgI_mmiq2yYdbZZwtKWDOUkMcouQekeCjNg4L0NEtKIbN7Ljxuu8XNN1xZpEcRTIC8b5TV7PeH-Te81V_cpRsaKl4kJHZsFLq1DJej3j8U4FMywUEQpjq29IcrpNpp-RGavKFYpSZ-Kj1OTKCKO8E-goo8v5kwBEXt1lE6SfW-vIhbnw',
      expires_in: 43199,
      scope: 'read write trust',
      organ: {
        organId: '1',
        organName: '河北省生态环境厅',
        organCode: '130000000',
        organDesc: '机构描述001',
        organType: '1',
        parentId: '0',
        organPath: '/1',
        orderNum: 0,
        enable: '1',
        parentUnit: '1',
        organKind: '1'
      },
      realName: '管理员',
      loginId: 'admin',
      auth: 'AUTH_ADMIN,AUTH_AIR,AUTH_AIR_DATA_AUDIT1,AUTH_AIR_DEPT_MANAGE,AUTH_AIR_USER_MANAGE,AUTH_BOOK,AUTH_COAL_ADMIN,AUTH_COAL_BASE,AUTH_DISPATCH_MAP_ADMIN,AUTH_ER_EMERGENCY_CENTER,AUTH_FBJD_GKPT,AUTH_FBJD_HB,AUTH_FBJD_TRANSMIT,AUTH_FURNACE_SHENG,AUTH_FURNACE_SHI,AUTH_FURNACE_XIAN,AUTH_OL_CITY_JCJ,AUTH_OPERATE_OPERATE_ZF,AUTH_PDA_ALL_PUBLIC,AUTH_PDA_ALL_PUBLIC_APP,AUTH_PDA_APPLY_AUDIT,AUTH_PDA_CHUZHIDANFUHE,AUTH_PDA_COAL_QUALITY_APP,AUTH_PDA_INSPECTCHECK_APP,AUTH_PDA_SHENG_LEADER,AUTH_PDA_SHENG_LEADER_APP,AUTH_PDA_SHENG_NORMAL_APP,AUTH_PDA_SHENG_RANDOM,AUTH_PDA_SHENG_RANDOM_APP,AUTH_PDA_SHENG_TIPSTAFF,AUTH_PDA_SHENG_TIPSTAFF_APP,AUTH_PDA_SPECIALBAIYANGDIAN_APP,AUTH_PDA_SPECIALINSPECTOR_APP,AUTH_PDA_TIPSTAFF_MANAGE,AUTH_PSDMPROXY_ADMIN,AUTH_TOKEN,AUTH_VD_MENU_MANAGER,AUTH_XZCF,AUTH_ZHPS_PS,auth_unifiedbaseinfo_admin,三线一单权限',
      roles:
        'ROLE_PDA_SHENG_RANDOM,ROLE_ADMIN,ROLE_XZCF,ROLE_PDA_SHENG_TIPSTAFF,ROLE_COAL,ROLE_FURNACE_ADMIN,ROLE_PSDMPROXY_ADMIN,ROLE_PDA_SPECIALBAIYANGDIAN,ROLE_FBJD_HB,ROLE_PDA_ALL_PUBLIC,ROLE_VD_M_MENU,ROLE_PDA_SHENG_LEADER,ROLE_PDA_SHENG_NORMAL,role_unifiedbaseinfo_admin,ROLE_AIR_HUANBAOJU,ROLE_DISPATCH_MAP_ADMIN,ROLE_PDA_RANDOM_FLAG',
      mobile: '13623310337',
      id: '11',
      jti: 'faa2100d-edae-4842-8863-b38a88cf038e'
    };
  },
  'POST /register': {
    msg: 'ok'
  }
};
